json.extract! business, :id, 
                        :creator_id, 
                        :category, 
                        :street, 
                        :city, 
                        :zip_code, 
                        :webpage, 
                        :phone_number, 
                        :state, 
                        :price